jramon1/bartuur-app

- config/routes.rb
added the routes to routes.rb in config folder
> Made the routes

- app/assets/stylesheets/config/_variables.scss
added a palette of colours to the variable stylesheet @waltervanwoudenberg
> Add colour palette on variables

- app/assets/stylesheets/config/_variables.scss
- db/schema.rb
> change the universal header font

- app/controllers/account/products_controller.rb
- app/views/account/products/index.html.erb
- app/views/account/products/new.html.erb
- config/application.yml
add-form-to-create-product-redirect-not-working-yet
> add-form-to-create-product-redirect-not-working-yet

- app/assets/javascripts/omniauth_callbacks_controller.coffee
- app/assets/stylesheets/omniauth_callbacks_controller.scss
- app/controllers/account/products_controller.rb
- app/controllers/products_controller.rb
- app/helpers/omniauth_callbacks_controller_helper.rb
- app/views/account/products/index.html.erb
- app/views/account/products/new.html.erb
- app/views/account/products/show.html.erb
> functioning-add-product

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_product-show.scss
- app/controllers/application_controller.rb
- app/controllers/products_controller.rb
- app/views/products/show.html.erb
- db/seeds.rb
working on doing some front end stuff for the swiping @JurjenJM
> frontend styling for swiping cards

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/products/show.html.erb
- config/secrets.yml
Working on frontend swiping process @Micky0806
> frontend swiping edits

- app/assets/stylesheets/pages/account/_products-index.scss
- app/controllers/account/products_controller.rb
- app/models/product.rb
- app/views/account/products/index.html.erb
- app/views/account/products/new.html.erb
front-end-for-add-product-and-products-index
> front-end-for-add-product-and-products-index

- app/controllers/application_controller.rb
just uncommented the authentication @JurjenJM
> Uncomment authenticate

- app/assets/javascripts/application.js
- app/assets/javascripts/show_products.js
- app/assets/stylesheets/components/_avatars.scss
- app/assets/stylesheets/pages/_product-show.scss
- app/controllers/appreciations_controller.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/products/_show_product_info.html.erb
- app/views/products/show.html.erb
change the page with javascript and go back to the product page
> Page 5 mike

- app/assets/javascripts/profile_menu.js
- app/assets/stylesheets/pages/_product-show.scss
- app/assets/stylesheets/pages/account/_profile-show.scss
- app/controllers/account/profiles_controller.rb
- app/views/account/profiles/show.html.erb
> profile-settings-page

- app/controllers/account/products_controller.rb
- app/controllers/account/profiles_controller.rb
- app/views/account/products/_form.html.erb
- app/views/account/products/edit.html.erb
- app/views/account/products/new.html.erb
- app/views/account/profiles/show.html.erb
profile pages are all working :)
> profile pages are all working :)

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/account/_profile-show.scss
- app/models/user.rb
- app/views/account/profiles/show.html.erb
add-style-frontend-for-account-profile-page
> add-style-frontend-for-account-profile-page

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_deckend.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/products/deckend.html.erb
check dis out ! @JurjenJM  @waltervanwoudenberg  @Micky0806
> pulsing logo in deck end

- app/assets/stylesheets/pages/_deckend.scss
- app/assets/stylesheets/pages/account/_add-product-page.scss
- app/assets/stylesheets/pages/account/_profile-show.scss
- app/views/account/products/edit.html.erb
- app/views/account/products/new.html.erb
- app/views/account/profiles/show.html.erb
> some css fixes

- app/controllers/account/products_controller.rb
> routed updated product to profile

- app/views/products/deckend.html.erb
just changing the u's @JurjenJM
> bartuur U change

- app/assets/stylesheets/layout/_footer.scss
- app/assets/stylesheets/pages/_product-show.scss
- app/views/products/show.html.erb
- app/views/shared/_footer.html.erb
page show product done with round button
have to adapt give a shoot to the exchange one
> Product show

- app/controllers/account/matches_controller.rb
- app/controllers/account/messages_controller.rb
- app/views/shared/navbars/_arrow_user_product.html.erb
yoyo merge it for some work @Micky0806
> other user name on chat

- app/assets/javascripts/init_attachinary.js
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/account/_add-product-page.scss
- app/assets/stylesheets/pages/account/_form.scss
- app/assets/stylesheets/pages/account/_profile-show.scss
- app/models/product.rb
- app/views/account/products/_form.html.erb
- app/views/account/products/edit.html.erb
- app/views/account/products/index.html.erb
- app/views/account/products/new.html.erb
- app/views/account/profiles/show.html.erb
finished-all-account-settings-and-account-product-front-end
> finished-all-account-settings-and-account-product-front-end

- app/assets/javascripts/show_products.js
- app/assets/stylesheets/layout/_footer.scss
- app/assets/stylesheets/pages/_product-show.scss
- app/controllers/products_controller.rb
- app/views/layouts/application.html.erb
- app/views/products/show.html.erb
- app/views/products/show_description.html.erb
- app/views/shared/navbars/_arrow_user_product.html.erb
- config/routes.rb
the path is working
footer commented not working
> add path to product in message

- app/assets/stylesheets/pages/_product-show.scss
- app/views/products/show.html.erb
- db/seeds.rb
add some padding to the button to center them
and placed the value under the name more beautifull I thing
> add padding to the round button and place the value block under the name

- app/assets/stylesheets/layout/_footer.scss
- app/views/shared/_footer.html.erb
changed the footer button padding fixed
> changed footer button

- app/helpers/meta_tags_helper.rb
- app/views/layouts/application.html.erb
- app/views/products/show.html.erb
- config/meta.yml
> meta tags created

- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/views/layouts/application.html.erb
- app/views/products/show.html.erb
- config/environment.rb
- config/meta.yml
- db/schema.rb
will be working now @Micky0806 @JurjenJM
> fix metatags

- app/assets/stylesheets/layout/_footer.scss
- app/assets/stylesheets/pages/_product-show.scss
- app/views/products/show.html.erb
- app/views/shared/_footer.html.erb
- db/seeds.rb
footer fixed with round button
> Mike footer button

- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
Jquery for disappearing notices when signed in works now @Micky0806 @JurjenJM @waltervanwoudenberg
> Javascript disappearing message

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/account/_profile-show.scss
- app/controllers/account/products_controller.rb
- app/controllers/account/profiles_controller.rb
- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/account/profiles/show.html.erb
- db/migrate/20160627095755_add_coordinates_to_users.rb
- db/migrate/20160627121307_add_distance_to_users.rb
- db/migrate/20160627132143_rename_distance_for_users.rb
- db/schema.rb
- db/seeds.rb
> add geocoder

- app/assets/javascripts/application.js
- app/assets/stylesheets/components/_alert.scss
- app/controllers/account/profiles_controller.rb
- app/controllers/appreciations_controller.rb
- app/views/account/profiles/show.html.erb
- app/views/shared/_flashes.html.erb
check this out, its working! will add styling @Micky0806  @JurjenJM @waltervanwoudenberg
> pop up when there is a match

- app/assets/stylesheets/pages/account/_chat.scss
- app/controllers/account/matches_controller.rb
- app/views/account/matches/show.html.erb
- app/views/account/products/_form.html.erb
- app/views/shared/navbars/_arrow_user_product.html.erb
Apparently there is a merge conflict...
I will check it out.
> Match since

- app/assets/stylesheets/layout/_footer.scss
- app/views/shared/_footer.html.erb
footer fixed
from here everything is good according to me
> add fixed to the footer and transparency

- app/assets/stylesheets/pages/account/_chat.scss
- app/views/account/matches/show.html.erb
> Stick new message form to bottom

- app/assets/stylesheets/layout/_footer.scss
- app/assets/stylesheets/pages/_product-show.scss
- app/views/products/show.html.erb
- app/views/shared/_footer.html.erb
> show page done following design nicole

- app/assets/stylesheets/components/_avatars.scss
- app/assets/stylesheets/components/_badges.scss
- app/assets/stylesheets/layout/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_product-show.scss
- app/assets/stylesheets/pages/account/_form.scss
- app/assets/stylesheets/pages/account/_matches.scss
- app/assets/stylesheets/pages/account/_profile-show.scss
- app/views/account/products/new.html.erb
- app/views/account/profiles/show.html.erb
- app/views/pages/home.html.erb
- app/views/shared/navbars/_arrow_user_product.html.erb
Jo guys I optimized our website for mobile screen sizes.
I think It looks pretty nice now on a phone. Check it out on your phone and let me know what you guys think!
> Overall styling of website

- app/assets/stylesheets/pages/account/_profile-show.scss
- app/views/account/profiles/show.html.erb
- app/views/devise/sessions/new.html.erb
add changes to the profile products page
> add changes to the profile products page

- app/assets/stylesheets/config/_variables.scss
for u waltaaaaaaaaaaah @waltervanwoudenberg
> add color clear gray to variables

- app/assets/stylesheets/pages/account/_matches.scss
- app/controllers/account/profiles_controller.rb
- app/controllers/appreciations_controller.rb
- app/controllers/products_controller.rb
- app/views/account/matches/_match.html.erb
- app/views/shared/_flashes.html.erb
- db/seeds.rb
check diss shiaaat out dawwwg @JurjenJM @Micky0806 @waltervanwoudenberg
> Popup frontend match
